"""Initial production schema

Revision ID: 0e41342906a4
Revises: 
Create Date: 2026-07-10 13:39:25.379441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e41342906a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('super_admin', 'admin', 'user', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('original_url', sa.Text(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('campaign', sa.String(length=120), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('location_name', sa.String(length=160), nullable=True),
    sa.Column('locality', sa.String(length=120), nullable=True),
    sa.Column('placement_type', sa.String(length=80), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('click_count', sa.Integer(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_links_campaign'), ['campaign'], unique=False)
        batch_op.create_index(batch_op.f('ix_links_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_links_click_count'), ['click_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_links_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_links_locality'), ['locality'], unique=False)
        batch_op.create_index(batch_op.f('ix_links_slug'), ['slug'], unique=True)

    op.create_table('media_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('object_key', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('media_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_assets_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_assets_checksum_sha256'), ['checksum_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_assets_object_key'), ['object_key'], unique=False)

    op.create_table('two_factor_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qr_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('fill_color', sa.String(length=20), nullable=False),
    sa.Column('back_color', sa.String(length=20), nullable=False),
    sa.Column('error_correction', sa.String(length=5), nullable=False),
    sa.Column('generated_url', sa.Text(), nullable=False),
    sa.Column('has_logo', sa.Boolean(), nullable=False),
    sa.Column('logo_object_key', sa.String(length=255), nullable=True),
    sa.Column('logo_path', sa.String(length=255), nullable=True),
    sa.Column('logo_original_name', sa.String(length=200), nullable=True),
    sa.Column('logo_mime_type', sa.String(length=100), nullable=True),
    sa.Column('logo_asset_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['link_id'], ['links.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['logo_asset_id'], ['media_assets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('qr_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qr_codes_link_id'), ['link_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_qr_codes_logo_asset_id'), ['logo_asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_qr_codes_logo_object_key'), ['logo_object_key'], unique=False)

    op.create_table('click_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('qr_code_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('ip_anonymized', sa.String(length=45), nullable=True),
    sa.Column('user_agent_raw', sa.Text(), nullable=True),
    sa.Column('browser', sa.String(length=80), nullable=True),
    sa.Column('browser_version', sa.String(length=80), nullable=True),
    sa.Column('os', sa.String(length=80), nullable=True),
    sa.Column('os_version', sa.String(length=80), nullable=True),
    sa.Column('device_type', sa.String(length=40), nullable=True),
    sa.Column('device_family', sa.String(length=120), nullable=True),
    sa.Column('referrer', sa.Text(), nullable=True),
    sa.Column('accept_language', sa.String(length=255), nullable=True),
    sa.Column('primary_language', sa.String(length=20), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('is_bot', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['link_id'], ['links.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['qr_code_id'], ['qr_codes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('click_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_click_events_browser'), ['browser'], unique=False)
        batch_op.create_index(batch_op.f('ix_click_events_device_type'), ['device_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_click_events_ip_hash'), ['ip_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_click_events_is_bot'), ['is_bot'], unique=False)
        batch_op.create_index(batch_op.f('ix_click_events_link_id'), ['link_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_click_events_os'), ['os'], unique=False)
        batch_op.create_index(batch_op.f('ix_click_events_primary_language'), ['primary_language'], unique=False)
        batch_op.create_index(batch_op.f('ix_click_events_qr_code_id'), ['qr_code_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_click_events_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # Dropping dependent tables also drops their FK-backed indexes. Explicit
    # index removal first fails on MariaDB because those indexes are required
    # by active foreign key constraints.
    op.drop_table('click_events')
    op.drop_table('qr_codes')
    op.drop_table('two_factor_codes')
    op.drop_table('links')
    op.drop_table('media_assets')
    op.drop_table('activity_logs')
    op.drop_table('users')
